export const problems = [
  {
    number: 1,
    title: "Two Sum",
    exp: "return the sum of two number given",
    ex: ["1 \n 2", "3 \n 5"],
    exout: ["3", "8"],
    output: [],
    level: "L1",
    tags: [],
    imageLink: "",
    testcases: [],
  },
  {
    number: 2,
    title: "greater element",
    exp: "print the number which is greater",
    ex: ["1 \n 2", "3 \n 5"],
    exout: ["2", "5"],
    output: [],
    level: "L1",
    tags: [],
    imageLink: "",
    testcases: [],
  },
  {
    number: 3,
    title: "Difference",
    exp: "return the absolute difference between two numbers",
    ex: ["5 \n 3", "10 \n 7"],
    exout: ["2", "3"],
    output: [],
    level: "L1",
    tags: [],
    imageLink: "",
    testcases: [],
  },
  {
    number: 4,
    title: "Smaller Element",
    exp: "print the number which is smaller",
    ex: ["7 \n 3", "9 \n 12"],
    exout: ["3", "9"],
    output: [],
    level: "L1",
    tags: [],
    imageLink: "",
    testcases: [],
  },
  {
    number: 7,
    title: "Modulo",
    exp: "return the remainder when first number is divided by second number",
    ex: ["10 \n 3", "17 \n 5"],
    exout: ["1", "2"],
    output: [],
    level: "L1",
    tags: [],
    imageLink: "",
    testcases: [],
  },
];
